config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:index, :show, :new, :create]
  end
  resources :reviews, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, foreign_key: "restaurant_id", dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant
  def new
    @review = Review.new
  end
  
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to restaurant_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORY %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="col">
    <div class="cards">
      <h1>List of Restaurants</h1>
      <% @restaurants.each do |restaurant| %>
        <div class="card-product">
          <div class="card-product-infos">
            <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="col">
    <h1>Add new restaurant</h1>
    <%= render 'restaurants/form' %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="col">
    <div class="cards">
      <h1>Restaurant</h1>
        <div class="card-product">
          <div class="card-product-infos">
            <h3><%= @restaurant.name %></h3>
            <p><%= @restaurant.address %></p>
            <p><%= @restaurant.phone_number %></p>
            <p><%= @restaurant.category %></p>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit class: 'btn btn-danger' %>
<% end %>

app/views/reviews/show.html.erb
<%= link_to 'add a new review', new_restaurant_review_path(@restaurant) %>
<%= restaurant.reviews.each do |review| %>
<p><%= review.content %></p>
<p>rating :<%= review.rating %></p>
<hr>
<% end %>